name: 'Get the PR information'
description: 'Get the PR information'
inputs:
  prNumber:  
    description: 'PR Number'
    required: true

outputs:
  prInfo: # id of output
    description: 'pr information'    
runs:
  using: 'node12'
  main: 'index.js'