name: 'Get the PR information'
description: 'Get the PR information'
inputs:
  prNumber:  
    description: 'PR Number'
    required: true
  repository:
    description: The owner and repository name, in the format <owner>/<repo>.
    default: ${{ github.repository }}
    required: false
outputs:
  prInfo: # id of output
    description: 'pr information'    
runs:
  using: 'node12'
  main: 'index.js'