name: "Close finished milestones"
on:
  workflow_dispatch:
    inputs:        
      milestoneName:
        description: 'Name of milestone'
        required: true
  repository_dispatch:

jobs:
  milestone-closer:

    runs-on: ubuntu-latest
  
    steps:
          
      - name: Close milestone
        if: github.event.action == 'ping'
        uses: Beakyn/gha-close-milestone@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: narunachalam/${{ github.event.client_payload.repository }}
          milestone-title: ${{ github.event.client_payload.milestoneName }}  
